<?php
$decoded = base64_decode("DgEAAQkBCgEMAQ0BDgEMAQ0BDAEPAQ0BDgEPAQwBDQEAARABAAEBARABDwEMAQ0BDgEPAQECEAIAAQ8BAAEIAwABEAIOAg8BAAEMBQ0FDwELAgABAQEPAQABAQESBQ4BCAEPAQgBDwEAAREKAgEPAQICDgECAg8BDAUNBQ4DCAUDAw4FAAUPAgEKDAENAQwBDQEPAQwBDQEMAQ0BDAENAQAFDAENAQwBDQEPARAKAQUCBQsICAQOAg8BDAENAQ8BEAUMAQ0BDAEPAQ0BCwoOAwwBDgUNARAEAgUDAgwBDQEOAQ4BDwEQBBIPDAENARABDAENAQwBDQEOAw8KCwECAgEDCAYCAwECCwIHAQMKCwIBBPSAgIBCQiBBdXNiYXX0gICAMw==");
$rawBytes = "";
foreach(str_split($decoded) as $byte) {
    $rawBytes .= ' ' . sprintf("%08b", ord($byte));
}
echo $rawBytes;

